/**
 * KDS-Compliant Dashboard Template
 * Generated by KIE v3 - Story Manifest Dashboard
 *
 * Enforces KDS design system:
 * - NO arbitrary colors (no green/yellow/red/blue)
 * - Uses KDS palette only (purple family + neutrals)
 * - Feather-style icons (lucide-react)
 * - Restrained typography scale
 * - Semantic badge variants
 */

import { useState, useEffect } from 'react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  LabelList,
} from 'recharts';
import { Card, CardHeader, CardTitle, CardContent } from './components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './components/ui/tabs';
import { AlertCircle } from 'lucide-react';

interface Visual {
  chart_ref: string;
  visualization_type: string;
  visual_quality: string;
  role: string;
  transition_text: string;
  emphasis: string;
}

interface Narrative {
  headline: string;
  bullets?: string[];
  purpose?: string;
}

interface Section {
  title: string;
  actionability_level: string;
  narrative: Narrative;
  visuals: Visual[];
}

interface StoryManifest {
  project_name: string;
  objective: string;
  generated_at?: string;
  sections: Section[];
}

interface ChartData {
  type: string;
  data: any[];
  config: any;
}

// KDS-compliant badge component (inline to avoid extra files)
interface BadgeProps {
  variant: 'decision' | 'direction' | 'info' | 'ok' | 'caveat' | 'internal';
  label: string;
}

function Badge({ variant, label }: BadgeProps) {
  const styles = {
    decision: 'bg-primary text-white border-primary',
    direction: 'bg-transparent text-primary border-primary',
    info: 'bg-muted/30 text-muted-foreground border-border',
    ok: 'bg-primary/10 text-primary border-primary/30',
    caveat: 'bg-muted text-foreground border-border',
    internal: 'bg-charcoal text-muted-foreground border-muted',
  };

  return (
    <span
      className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-xs font-medium border ${styles[variant]}`}
    >
      {label}
    </span>
  );
}

export function Dashboard() {
  const [manifest, setManifest] = useState<StoryManifest | null>(null);
  const [charts, setCharts] = useState<Record<string, ChartData>>({});
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // Fetch story manifest
    fetch('/story_manifest.json')
      .then((res) => {
        if (!res.ok) throw new Error('Story manifest not found');
        return res.json();
      })
      .then((data: StoryManifest) => {
        setManifest(data);

        // Fetch all chart specs
        const chartPromises = data.sections.flatMap((section) =>
          section.visuals.map((visual) =>
            fetch(`/charts/${visual.chart_ref}`)
              .then((res) => res.json())
              .then((chartData) => [visual.chart_ref, chartData] as const)
          )
        );

        return Promise.all(chartPromises);
      })
      .then((chartEntries) => {
        const chartsMap: Record<string, ChartData> = {};
        chartEntries.forEach(([ref, data]) => {
          chartsMap[ref] = data;
        });
        setCharts(chartsMap);
      })
      .catch((err) => {
        console.error('Error loading manifest or charts:', err);
        setError(err.message);
      });
  }, []);

  if (error) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center p-6">
        <Card className="p-6 max-w-lg">
          <div className="flex items-start gap-4">
            <AlertCircle className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
            <div>
              <h3 className="font-semibold mb-2">Dashboard Error</h3>
              <p className="text-sm text-muted-foreground mb-4">
                Unable to load story manifest: {error}
              </p>
              <p className="text-sm text-muted-foreground">
                Ensure the /build command has been run and story_manifest.json
                exists.
              </p>
            </div>
          </div>
        </Card>
      </div>
    );
  }

  if (!manifest) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <p className="text-muted-foreground">Loading story...</p>
      </div>
    );
  }

  // Classify sections into Main Story vs Appendix
  const mainStorySections: Section[] = [];
  const appendixSections: Section[] = [];

  manifest.sections.forEach((section) => {
    const isDecisionEnabling =
      section.actionability_level === 'decision_enabling';
    const hasInternalOnlyVisual = section.visuals.some(
      (v) => v.visual_quality === 'internal_only'
    );

    if (isDecisionEnabling && !hasInternalOnlyVisual) {
      mainStorySections.push(section);
    } else {
      appendixSections.push(section);
    }
  });

  const renderChart = (visual: Visual) => {
    const chartSpec = charts[visual.chart_ref];
    if (!chartSpec) {
      return (
        <div className="text-sm text-muted-foreground">
          Loading chart: {visual.chart_ref}
        </div>
      );
    }

    // Render bar chart
    if (
      chartSpec.type === 'bar' &&
      chartSpec.config?.xAxis &&
      chartSpec.config?.bars?.[0]
    ) {
      const xKey = chartSpec.config.xAxis.dataKey;
      const yKey = chartSpec.config.bars[0].dataKey;
      const barColor = chartSpec.config.bars[0].fill || 'var(--chart-10)';

      return (
        <ResponsiveContainer width="100%" height={300}>
          <BarChart data={chartSpec.data}>
            <XAxis
              dataKey={xKey}
              axisLine={false}
              tickLine={false}
              tick={{ fill: 'currentColor', fontSize: 12 }}
            />
            <YAxis axisLine={false} tickLine={false} tick={false} />
            <Tooltip
              contentStyle={{
                backgroundColor: 'hsl(var(--card))',
                border: '1px solid hsl(var(--border))',
                borderRadius: '8px',
              }}
            />
            <Bar dataKey={yKey} fill={barColor} radius={[4, 4, 0, 0]}>
              <LabelList
                dataKey={yKey}
                position="top"
                style={{ fill: 'currentColor', fontSize: 14, fontWeight: 600 }}
              />
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      );
    }

    return (
      <div className="text-sm text-muted-foreground">
        Unsupported chart type: {chartSpec.type}
      </div>
    );
  };

  const getActionabilityBadge = (level: string): BadgeProps => {
    const badges: Record<string, BadgeProps> = {
      decision_enabling: { variant: 'decision', label: 'DECISION' },
      directional: { variant: 'direction', label: 'DIRECTION' },
      informational: { variant: 'info', label: 'INFO' },
    };
    return badges[level] || badges.informational;
  };

  const getVisualQualityBadge = (quality: string): BadgeProps => {
    const badges: Record<string, BadgeProps> = {
      client_ready: { variant: 'ok', label: 'OK' },
      client_ready_with_caveats: { variant: 'caveat', label: '⚠️ Caveat' },
      internal_only: { variant: 'internal', label: 'Internal Only' },
    };
    return badges[quality] || { variant: 'ok', label: 'OK' };
  };

  const renderSection = (section: Section) => {
    const actionabilityBadge = getActionabilityBadge(
      section.actionability_level
    );

    return (
      <section key={section.title} className="space-y-6">
        {/* Section Header */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <h2 className="text-2xl font-bold tracking-tight">
              {section.title}
            </h2>
            <Badge
              variant={actionabilityBadge.variant}
              label={actionabilityBadge.label}
            />
          </div>

          {section.narrative.purpose && (
            <p className="text-sm text-muted-foreground">
              {section.narrative.purpose}
            </p>
          )}

          <div className="border-l-4 border-primary/30 pl-4 py-2">
            <h3 className="text-lg font-semibold mb-3">
              {section.narrative.headline}
            </h3>
            {section.narrative.bullets && section.narrative.bullets.length > 0 && (
              <ul className="space-y-2">
                {section.narrative.bullets.map((bullet, idx) => (
                  <li key={idx} className="flex items-start gap-3">
                    <span className="text-primary mt-0.5">•</span>
                    <span className="text-sm text-muted-foreground flex-1">
                      {bullet}
                    </span>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>

        {/* Visuals */}
        {section.visuals.length > 0 ? (
          <div className="space-y-6">
            {section.visuals.map((visual, idx) => {
              const qualityBadge = getVisualQualityBadge(visual.visual_quality);
              return (
                <Card key={idx} className="overflow-hidden">
                  <CardHeader className="space-y-2">
                    <div className="flex items-center justify-between">
                      <CardTitle className="text-base font-semibold">
                        {visual.role}
                      </CardTitle>
                      <Badge
                        variant={qualityBadge.variant}
                        label={qualityBadge.label}
                      />
                    </div>
                    <p className="text-sm text-muted-foreground">
                      {visual.transition_text}
                    </p>
                  </CardHeader>
                  <CardContent className="pb-6">{renderChart(visual)}</CardContent>
                </Card>
              );
            })}
          </div>
        ) : (
          <Card className="p-6">
            <p className="text-sm text-muted-foreground text-center">
              No visuals required for this section.
            </p>
          </Card>
        )}
      </section>
    );
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Page Header */}
      <header className="border-b border-border bg-card/50">
        <div className="max-w-5xl mx-auto px-6 py-8">
          <h1 className="text-3xl font-bold tracking-tight mb-3">
            {manifest.project_name}
          </h1>
          <p className="text-base text-muted-foreground mb-2">
            {manifest.objective}
          </p>
          {manifest.generated_at && (
            <p className="text-xs text-muted-foreground">
              Generated: {new Date(manifest.generated_at).toLocaleString()}
            </p>
          )}
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-5xl mx-auto px-6 py-8">
        <Tabs defaultValue="main-story" className="space-y-8">
          <TabsList className="grid w-full max-w-md grid-cols-2">
            <TabsTrigger value="main-story" className="text-sm font-medium">
              Main Story
            </TabsTrigger>
            <TabsTrigger value="appendix" className="text-sm font-medium">
              Appendix
            </TabsTrigger>
          </TabsList>

          <TabsContent value="main-story" className="space-y-10">
            {mainStorySections.length > 0 ? (
              mainStorySections.map(renderSection)
            ) : (
              <Card className="p-8">
                <p className="text-muted-foreground text-center">
                  No main story sections available.
                </p>
              </Card>
            )}
          </TabsContent>

          <TabsContent value="appendix" className="space-y-10">
            {appendixSections.length > 0 ? (
              appendixSections.map(renderSection)
            ) : (
              <Card className="p-8">
                <p className="text-muted-foreground text-center">
                  No appendix sections available.
                </p>
              </Card>
            )}
          </TabsContent>
        </Tabs>
      </main>

      {/* Footer */}
      <footer className="border-t border-border mt-16">
        <div className="max-w-5xl mx-auto px-6 py-6">
          <p className="text-center text-sm text-muted-foreground">
            {manifest.project_name} | Generated with KIE v3 | Story Manifest
            Dashboard
          </p>
        </div>
      </footer>
    </div>
  );
}
