"""
Streamlit Dashboard Builder for KIE v3 - KDS COMPLIANT

Generates KDS-compliant Streamlit apps following official Kearney Design System rules:
- NO gridlines
- Value labels on all data points
- Hide Y-axis when labels present
- Inter font family
- Official KDS color palette
"""

from pathlib import Path
from typing import Dict, Any, List
import json


KDS_PLOTLY_LAYOUT = """
# KDS-Compliant Plotly Configuration
def apply_kds_layout(fig, title=""):
    '''Apply KDS styling to Plotly figure'''
    fig.update_layout(
        title=dict(text=title, font=dict(family='Inter, Arial, sans-serif', size=18, color='white')),
        plot_bgcolor=KEARNEY_BG,
        paper_bgcolor=KEARNEY_BG,
        font=dict(family='Inter, Arial, sans-serif', size=12, color='white'),
        xaxis=dict(
            showgrid=False,  # KDS: NO GRIDLINES
            showline=False,  # KDS: NO AXIS LINES
            tickfont=dict(size=12)
        ),
        yaxis=dict(
            showgrid=False,  # KDS: NO GRIDLINES
            showline=False,  # KDS: NO AXIS LINES
            showticklabels=False  # KDS: Hide when labels present
        ),
        showlegend=True,
        legend=dict(font=dict(size=12))
    )
    return fig
"""


class StreamlitDashboardBuilder:
    """Build KDS-compliant Streamlit dashboards."""

    def __init__(self, project_name: str, client_name: str, objective: str):
        self.project_name = project_name
        self.client_name = client_name
        self.objective = objective

    def build_dashboard(
        self,
        data_path: Path,
        charts_dir: Path,
        output_path: Path,
        theme_mode: str = "dark"
    ) -> Path:
        """Build Streamlit dashboard."""
        code = self._generate_streamlit_code(data_path, theme_mode)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(code)
        return output_path

    def _generate_streamlit_code(self, data_path: Path, theme_mode: str) -> str:
        """Generate KDS-compliant Streamlit code."""

        code = f'''"""
{self.project_name}
Generated by KIE v3 - KDS Compliant
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Kearney Design System Colors (Official KDS Palette)
KEARNEY_PRIMARY = "#7823DC"
KEARNEY_ACCENT = "#9B4DCA"
KEARNEY_LIGHT = "#C4A6E8"
KEARNEY_DARK = "#5B1BA9"
KEARNEY_BG = "#1E1E1E"
KDS_CHART_COLORS = ["#D2D2D2", "#A5A6A5", "#787878", "#E0D2FA", "#C8A5F0",
                     "#AF7DEB", "#4B4B4B", "#1E1E1E", "#9150E1", "#7823DC"]

{KDS_PLOTLY_LAYOUT}

# Page config
st.set_page_config(
    page_title="{self.project_name}",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# KDS Custom CSS
st.markdown(\'\'\'
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');

    * {{
        font-family: Inter, Arial, sans-serif !important;
    }}
    .main {{
        background-color: #1E1E1E;
        color: #FFFFFF;
    }}
    .stMetric {{
        background-color: #2A2A2A;
        padding: 1rem;
        border-radius: 0.5rem;
        border-left: 4px solid #7823DC;
    }}
    .stMetric label {{
        color: #9B4DCA !important;
        font-size: 0.875rem;
        text-transform: uppercase;
        letter-spacing: 0.05em;
    }}
    h1, h2, h3 {{
        color: #FFFFFF !important;
        font-weight: 700;
    }}
    h1 {{ font-size: 2.5rem; }}
    h2 {{ font-size: 2rem; }}
    h3 {{ font-size: 1.5rem; }}
</style>
\'\'\', unsafe_allow_html=True)

# Load data
@st.cache_data
def load_data():
    return pd.read_csv('{data_path}')

df = load_data()
we_df = df[df['company'] == '{self.client_name}']
comp_df = df[df['company'] != '{self.client_name}']

# Header
st.markdown(f"""
<div style='background: linear-gradient(135deg, {{KEARNEY_PRIMARY}} 0%, {{KEARNEY_DARK}} 100%);
     padding: 2rem; border-radius: 0.5rem; margin-bottom: 2rem;'>
    <h1 style='margin: 0; color: white; font-size: 2.5rem;'>{self.project_name}</h1>
    <p style='margin: 0.5rem 0 0 0; color: white; opacity: 0.9; font-size: 1.125rem;'>{self.objective}</p>
</div>
""", unsafe_allow_html=True)

# Sidebar Filters
st.sidebar.header("Filters")
all_states = sorted(we_df['state'].unique())
selected_states = st.sidebar.multiselect("Select States", options=all_states, default=all_states)
territories = ['High-Value Market', 'Competitive Market', 'Low-Value Market']
selected_territories = st.sidebar.multiselect("Territory Type", options=territories, default=territories)

# Filter data
filtered_we = we_df[
    (we_df['state'].isin(selected_states)) &
    (we_df['revised_territory'].isin(selected_territories))
]

# KPI Metrics
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric("WE Locations", f"{{len(filtered_we):,}}",
              f"{{len(filtered_we)/len(we_df)*100:.1f}}% of total")
with col2:
    avg_score = filtered_we['revised_score'].mean()
    mkt_avg = df['revised_score'].mean()
    st.metric("Avg Performance Score", f"{{avg_score:.1f}}",
              f"{{(avg_score/mkt_avg-1)*100:+.1f}}% vs market")
with col3:
    total_opp = filtered_we['opportunity_millions'].sum()
    st.metric("Total Opportunity", f"${{total_opp:,.0f}}M",
              f"{{total_opp/df['opportunity_millions'].sum()*100:.1f}}% of market")
with col4:
    high_value = (filtered_we['revised_territory'] == 'High-Value Market').sum()
    st.metric("High-Value Locations", f"{{high_value}}",
              f"{{high_value/len(filtered_we)*100:.1f}}%" if len(filtered_we) > 0 else "0%")

# Tabs
tab1, tab2, tab3 = st.tabs(["📊 Overview", "🗺️ Geographic", "⚔️ Competitive"])

with tab1:
    st.header("Performance Overview")
    col1, col2 = st.columns(2)

    with col1:
        # Performance Comparison - KDS COMPLIANT
        perf_data = pd.DataFrame({{
            'Category': ['{self.client_name}', 'Market Average'],
            'Score': [we_df['revised_score'].mean(), df['revised_score'].mean()]
        }})
        fig = px.bar(perf_data, x='Category', y='Score', text='Score',
                     color='Category',
                     color_discrete_map={{'{self.client_name}': KEARNEY_PRIMARY,
                                        'Market Average': KEARNEY_ACCENT}})
        fig.update_traces(texttemplate='%{{text:.1f}}', textposition='outside',
                         textfont=dict(size=14, family='Inter, Arial, sans-serif'))
        fig = apply_kds_layout(fig, 'Performance Score: WE vs Market')
        fig.update_layout(showlegend=False)
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        # Territory Distribution - KDS COMPLIANT
        territory_data = []
        for territory in territories:
            territory_data.append({{
                'Territory': territory.replace(' Market', ''),
                '{self.client_name}': (we_df['revised_territory'] == territory).sum(),
                'Market': (df['revised_territory'] == territory).sum()
            }})
        territory_df = pd.DataFrame(territory_data)

        fig = go.Figure()
        fig.add_trace(go.Bar(name='{self.client_name}', x=territory_df['Territory'],
                            y=territory_df['{self.client_name}'], marker_color=KEARNEY_PRIMARY,
                            text=territory_df['{self.client_name}'], textposition='outside'))
        fig.add_trace(go.Bar(name='Market', x=territory_df['Territory'],
                            y=territory_df['Market'], marker_color=KEARNEY_ACCENT,
                            text=territory_df['Market'], textposition='outside'))
        fig = apply_kds_layout(fig, 'Territory Distribution')
        fig.update_layout(barmode='group')
        st.plotly_chart(fig, use_container_width=True)

with tab2:
    st.header("Geographic Analysis")

    # Top States - KDS COMPLIANT
    we_states = filtered_we.groupby('state').agg({{
        'lo_id': 'count',
        'opportunity_millions': 'sum'
    }}).sort_values('opportunity_millions', ascending=False).head(10).reset_index()

    fig = px.bar(we_states, x='state', y='opportunity_millions', text='opportunity_millions',
                 color='opportunity_millions',
                 color_continuous_scale=[[0, KEARNEY_LIGHT], [0.5, KEARNEY_ACCENT], [1, KEARNEY_PRIMARY]])
    fig.update_traces(texttemplate='$%{{text:.0f}}M', textposition='outside',
                     textfont=dict(size=12, family='Inter, Arial, sans-serif'))
    fig = apply_kds_layout(fig, 'Top 10 States by Opportunity')
    st.plotly_chart(fig, use_container_width=True)

    # Performance vs Opportunity Scatter - KDS COMPLIANT
    fig = px.scatter(filtered_we, x='revised_score', y='opportunity_millions',
                     color='revised_territory', hover_data=['city', 'state'],
                     color_discrete_map={{
                         'High-Value Market': KEARNEY_PRIMARY,
                         'Competitive Market': KEARNEY_ACCENT,
                         'Low-Value Market': KEARNEY_LIGHT
                     }})
    fig = apply_kds_layout(fig, 'Performance vs Opportunity')
    fig.update_layout(yaxis=dict(showticklabels=True))  # Show Y-axis for scatter
    st.plotly_chart(fig, use_container_width=True)

with tab3:
    st.header("Competitive Landscape")
    col1, col2 = st.columns(2)

    with col1:
        # Competitive Pressure - KDS COMPLIANT
        pressure_data = pd.DataFrame({{
            'Category': ['Low (<1.0)', 'Medium (1-2)', 'High (>2.0)'],
            'Locations': [
                (filtered_we['weighted_pressure'] < 1.0).sum(),
                ((filtered_we['weighted_pressure'] >= 1.0) &
                 (filtered_we['weighted_pressure'] <= 2.0)).sum(),
                (filtered_we['weighted_pressure'] > 2.0).sum()
            ]
        }})
        fig = px.bar(pressure_data, x='Category', y='Locations', text='Locations',
                     color='Category',
                     color_discrete_sequence=[KEARNEY_LIGHT, KEARNEY_ACCENT, KEARNEY_PRIMARY])
        fig.update_traces(texttemplate='%{{text}}', textposition='outside',
                         textfont=dict(size=14, family='Inter, Arial, sans-serif'))
        fig = apply_kds_layout(fig, 'Competitive Pressure Distribution')
        fig.update_layout(showlegend=False)
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader("Top 10 Competitors")
        top_comps = comp_df['company'].value_counts().head(10).reset_index()
        top_comps.columns = ['Company', 'Locations']
        st.dataframe(top_comps, use_container_width=True, hide_index=True)

# Footer
st.markdown("---")
st.markdown("""
<div style='text-align: center; color: #9B4DCA; padding: 1rem; font-size: 0.875rem;'>
    <p>{self.project_name} | Generated with KIE v3 | KDS Compliant</p>
</div>
""", unsafe_allow_html=True)
'''
        return code
