"""
Streamlit Dashboard Builder for KIE v3

Generates KDS-compliant Streamlit apps from chart configs and data.
"""

from pathlib import Path
from typing import Dict, Any, List, Optional
import json


class StreamlitDashboardBuilder:
    """Build Streamlit dashboards from KIE chart configs."""

    def __init__(self, project_name: str, client_name: str, objective: str):
        self.project_name = project_name
        self.client_name = client_name
        self.objective = objective

    def build_dashboard(
        self,
        data_path: Path,
        charts_dir: Path,
        output_path: Path,
        theme_mode: str = "dark"
    ) -> Path:
        """
        Build Streamlit dashboard.

        Args:
            data_path: Path to data CSV
            charts_dir: Directory with chart JSON configs
            output_path: Output path for dashboard.py
            theme_mode: Theme mode (dark or light)

        Returns:
            Path to generated dashboard
        """
        # Load chart configs
        chart_configs = []
        if charts_dir.exists():
            for config_file in sorted(charts_dir.glob("*.json")):
                with open(config_file) as f:
                    config = json.load(f)
                    chart_configs.append({
                        'name': config_file.stem,
                        'config': config
                    })

        # Generate Streamlit code
        code = self._generate_streamlit_code(
            data_path=data_path,
            chart_configs=chart_configs,
            theme_mode=theme_mode
        )

        # Write to file
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(code)

        return output_path

    def _generate_streamlit_code(
        self,
        data_path: Path,
        chart_configs: List[Dict[str, Any]],
        theme_mode: str
    ) -> str:
        """Generate Streamlit Python code."""

        # KDS colors
        kds_colors = """
# Kearney Design System Colors
KEARNEY_PRIMARY = "#7823DC"
KEARNEY_ACCENT = "#9B4DCA"
KEARNEY_LIGHT = "#C4A6E8"
KEARNEY_DARK = "#5B1BA9"
KEARNEY_BG = "#1E1E1E"
KDS_CHART_COLORS = [
    "#D2D2D2", "#A5A6A5", "#787878", "#E0D2FA", "#C8A5F0",
    "#AF7DEB", "#4B4B4B", "#1E1E1E", "#9150E1", "#7823DC"
]
"""

        # Custom CSS
        bg_color = "#1E1E1E" if theme_mode == "dark" else "#FFFFFF"
        text_color = "#FFFFFF" if theme_mode == "dark" else "#1E1E1E"

        custom_css = f"""
st.markdown('''
<style>
    .main {{{{
        background-color: {bg_color};
        color: {text_color};
    }}}}
    .stMetric {{{{
        background-color: #2A2A2A;
        padding: 1rem;
        border-radius: 0.5rem;
        border-left: 4px solid #7823DC;
    }}}}
    .stMetric label {{{{
        color: #9B4DCA !important;
    }}}}
    h1, h2, h3 {{{{
        color: {text_color} !important;
    }}}}
</style>
''', unsafe_allow_html=True)
"""

        code = f'''"""
{self.project_name}
Generated by KIE v3
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path

{kds_colors}

# Page config
st.set_page_config(
    page_title="{self.project_name}",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

{custom_css}

# Load data
@st.cache_data
def load_data():
    df = pd.read_csv('{data_path}')
    return df

df = load_data()

# Header
st.markdown(f"""
<div style='background: linear-gradient(135deg, {{KEARNEY_PRIMARY}} 0%, {{KEARNEY_DARK}} 100%);
     padding: 2rem; border-radius: 0.5rem; margin-bottom: 2rem;'>
    <h1 style='margin: 0; color: white;'>{self.project_name}</h1>
    <p style='margin: 0.5rem 0 0 0; color: white; opacity: 0.9;'>{self.objective}</p>
</div>
""", unsafe_allow_html=True)

# Split data
we_df = df[df['company'] == '{self.client_name}']
comp_df = df[df['company'] != '{self.client_name}']

# Sidebar filters
st.sidebar.header("Filters")
all_states = sorted(we_df['state'].unique())
selected_states = st.sidebar.multiselect(
    "Select States",
    options=all_states,
    default=all_states
)

territories = ['High-Value Market', 'Competitive Market', 'Low-Value Market']
selected_territories = st.sidebar.multiselect(
    "Territory Type",
    options=territories,
    default=territories
)

# Filter data
filtered_we = we_df[
    (we_df['state'].isin(selected_states)) &
    (we_df['revised_territory'].isin(selected_territories))
]

# Key Metrics
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        "WE Locations",
        f"{{len(filtered_we):,}}",
        f"{{len(filtered_we)/len(we_df)*100:.1f}}% of total"
    )

with col2:
    avg_score = filtered_we['revised_score'].mean()
    mkt_avg = df['revised_score'].mean()
    st.metric(
        "Avg Performance Score",
        f"{{avg_score:.1f}}",
        f"{{(avg_score/mkt_avg-1)*100:+.1f}}% vs market"
    )

with col3:
    total_opp = filtered_we['opportunity_millions'].sum()
    st.metric(
        "Total Opportunity",
        f"${{total_opp:,.0f}}M",
        f"{{total_opp/df['opportunity_millions'].sum()*100:.1f}}% of market"
    )

with col4:
    high_value = (filtered_we['revised_territory'] == 'High-Value Market').sum()
    st.metric(
        "High-Value Locations",
        f"{{high_value}}",
        f"{{high_value/len(filtered_we)*100:.1f}}%" if len(filtered_we) > 0 else "0%"
    )

# Tabs
tab1, tab2, tab3 = st.tabs(["📊 Overview", "🗺️ Geographic", "⚔️ Competitive"])

with tab1:
    st.header("Performance Overview")

    col1, col2 = st.columns(2)

    with col1:
        # Performance Comparison
        perf_data = pd.DataFrame({{
            'Category': ['{self.client_name}', 'Market Average'],
            'Performance Score': [we_df['revised_score'].mean(), df['revised_score'].mean()]
        }})
        fig = px.bar(
            perf_data, x='Category', y='Performance Score',
            title='Performance Score: WE vs Market',
            color='Category',
            color_discrete_map={{'{self.client_name}': KEARNEY_PRIMARY, 'Market Average': KEARNEY_ACCENT}},
            text='Performance Score'
        )
        fig.update_traces(texttemplate='%{{text:.1f}}', textposition='outside')
        fig.update_layout(
            plot_bgcolor=KEARNEY_BG,
            paper_bgcolor=KEARNEY_BG,
            font_color='white',
            showlegend=False,
            xaxis=dict(showgrid=False, showline=False),
            yaxis=dict(showgrid=False, showline=False, showticklabels=False),
            font=dict(family='Inter, Arial, sans-serif', size=12)
        )
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        # Territory Distribution
        territory_data = []
        for territory in territories:
            we_count = (we_df['revised_territory'] == territory).sum()
            mkt_count = (df['revised_territory'] == territory).sum()
            territory_data.append({{
                'Territory': territory.replace(' Market', ''),
                '{self.client_name}': we_count,
                'Market': mkt_count
            }})

        territory_df = pd.DataFrame(territory_data)
        fig = go.Figure()
        fig.add_trace(go.Bar(
            name='{self.client_name}',
            x=territory_df['Territory'],
            y=territory_df['{self.client_name}'],
            marker_color=KEARNEY_PRIMARY
        ))
        fig.add_trace(go.Bar(
            name='Market',
            x=territory_df['Territory'],
            y=territory_df['Market'],
            marker_color=KEARNEY_ACCENT
        ))
        fig.update_layout(
            title='Territory Distribution',
            barmode='group',
            plot_bgcolor=KEARNEY_BG,
            paper_bgcolor=KEARNEY_BG,
            font_color='white'
        )
        st.plotly_chart(fig, use_container_width=True)

with tab2:
    st.header("Geographic Analysis")

    # Top States
    we_states = filtered_we.groupby('state').agg({{
        'lo_id': 'count',
        'opportunity_millions': 'sum',
        'revised_score': 'mean'
    }}).sort_values('opportunity_millions', ascending=False).head(10).reset_index()

    fig = px.bar(
        we_states, x='state', y='opportunity_millions',
        title='Top 10 States by Opportunity',
        labels={{'opportunity_millions': 'Opportunity ($M)', 'state': 'State'}},
        color='revised_score',
        color_continuous_scale=[[0, KEARNEY_LIGHT], [0.5, KEARNEY_ACCENT], [1, KEARNEY_PRIMARY]]
    )
    fig.update_layout(
        plot_bgcolor=KEARNEY_BG,
        paper_bgcolor=KEARNEY_BG,
        font_color='white'
    )
    st.plotly_chart(fig, use_container_width=True)

    # Performance vs Opportunity
    fig = px.scatter(
        filtered_we,
        x='revised_score',
        y='opportunity_millions',
        color='revised_territory',
        hover_data=['city', 'state', 'competitor_count'],
        title='Performance vs Opportunity',
        labels={{
            'revised_score': 'Performance Score',
            'opportunity_millions': 'Opportunity ($M)',
            'revised_territory': 'Territory'
        }},
        color_discrete_map={{
            'High-Value Market': KEARNEY_PRIMARY,
            'Competitive Market': KEARNEY_ACCENT,
            'Low-Value Market': KEARNEY_LIGHT
        }}
    )
    fig.update_layout(
        plot_bgcolor=KEARNEY_BG,
        paper_bgcolor=KEARNEY_BG,
        font_color='white'
    )
    st.plotly_chart(fig, use_container_width=True)

with tab3:
    st.header("Competitive Landscape")

    col1, col2 = st.columns(2)

    with col1:
        # Competitive Pressure
        pressure_data = pd.DataFrame({{
            'Category': ['Low (<1.0)', 'Medium (1-2)', 'High (>2.0)'],
            'Locations': [
                (filtered_we['weighted_pressure'] < 1.0).sum(),
                ((filtered_we['weighted_pressure'] >= 1.0) &
                 (filtered_we['weighted_pressure'] <= 2.0)).sum(),
                (filtered_we['weighted_pressure'] > 2.0).sum()
            ]
        }})
        fig = px.bar(
            pressure_data, x='Category', y='Locations',
            title='Competitive Pressure Distribution',
            color='Category',
            color_discrete_sequence=[KEARNEY_LIGHT, KEARNEY_ACCENT, KEARNEY_PRIMARY]
        )
        fig.update_layout(
            plot_bgcolor=KEARNEY_BG,
            paper_bgcolor=KEARNEY_BG,
            font_color='white',
            showlegend=False
        )
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        # Top Competitors
        st.subheader("Top 10 Competitors")
        top_comps = comp_df['company'].value_counts().head(10).reset_index()
        top_comps.columns = ['Company', 'Locations']
        st.dataframe(top_comps, use_container_width=True)

# Footer
st.markdown("---")
st.markdown("""
<div style='text-align: center; color: #9B4DCA; padding: 1rem;'>
    <p>{self.project_name} | Generated with KIE v3</p>
</div>
""", unsafe_allow_html=True)
'''

        return code
