/**
 * Chart Renderer
 *
 * Generic component that consumes RechartsConfig JSON from Python backend
 * and routes to appropriate chart type renderer.
 */

import { useState, useEffect } from 'react';
import { BarChartRenderer } from './BarChartRenderer';
import { LineChartRenderer } from './LineChartRenderer';
import { AreaChartRenderer } from './AreaChartRenderer';
import { PieChartRenderer } from './PieChartRenderer';
import { ScatterChartRenderer } from './ScatterChartRenderer';
import { ComboChartRenderer } from './ComboChartRenderer';

interface RechartsConfig {
  type: 'bar' | 'line' | 'area' | 'pie' | 'scatter' | 'combo' | 'waterfall' | 'bullet';
  data: Array<Record<string, any>>;
  config: Record<string, any>;
  title?: string;
  subtitle?: string;
}

interface ChartRendererProps {
  config: RechartsConfig;
  className?: string;
}

/**
 * ChartRenderer - Main component for rendering charts
 *
 * Accepts a RechartsConfig object (from Python backend) and renders
 * the appropriate chart type with KDS compliance.
 */
export function ChartRenderer({ config, className = '' }: ChartRendererProps) {
  if (!config || !config.data) {
    return (
      <div className="flex items-center justify-center h-64 bg-bg-secondary rounded-lg border border-border-secondary">
        <p className="text-text-tertiary">No chart data available</p>
      </div>
    );
  }

  const chartContent = () => {
    switch (config.type) {
      case 'bar':
        return <BarChartRenderer config={config as any} />;
      case 'line':
        return <LineChartRenderer config={config as any} />;
      case 'area':
        return <AreaChartRenderer config={config as any} />;
      case 'pie':
        return <PieChartRenderer config={config as any} />;
      case 'scatter':
        return <ScatterChartRenderer config={config as any} />;
      case 'combo':
        return <ComboChartRenderer config={config as any} />;
      default:
        return (
          <div className="flex items-center justify-center h-64">
            <p className="text-text-tertiary">
              Chart type "{config.type}" not yet implemented
            </p>
          </div>
        );
    }
  };

  return (
    <div className={`bg-bg-secondary rounded-lg border border-border-secondary p-4 ${className}`}>
      {config.title && (
        <div className="mb-4">
          <h3 className="text-lg font-semibold text-text-primary">{config.title}</h3>
          {config.subtitle && (
            <p className="text-sm text-text-secondary mt-1">{config.subtitle}</p>
          )}
        </div>
      )}
      {chartContent()}
    </div>
  );
}

interface ChartLoaderProps {
  configPath: string;
  className?: string;
}

/**
 * ChartLoader - Loads chart config from JSON file path
 *
 * Use this when you have a path to a JSON file generated by Python.
 */
export function ChartLoader({ configPath, className = '' }: ChartLoaderProps) {
  const [config, setConfig] = useState<RechartsConfig | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setError(null);

    fetch(configPath)
      .then((res) => {
        if (!res.ok) {
          throw new Error(`Failed to load chart: ${res.statusText}`);
        }
        return res.json();
      })
      .then((data) => {
        setConfig(data);
        setLoading(false);
      })
      .catch((err) => {
        setError(err.message);
        setLoading(false);
      });
  }, [configPath]);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64 bg-bg-secondary rounded-lg border border-border-secondary">
        <p className="text-text-tertiary">Loading chart...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-64 bg-bg-secondary rounded-lg border border-border-secondary">
        <p className="text-error text-sm">Error: {error}</p>
      </div>
    );
  }

  if (!config) {
    return null;
  }

  return <ChartRenderer config={config} className={className} />;
}

export default ChartRenderer;
